### ISSUE TITLE
Config parameters have little or no effect.

### ISSUE THREAD

**Issue by RaeveNoir** [DoctorWiggles/GrimoireOfGaia#10] opened 2017-01-20 07:25 UTC
Changing the health or damage parameters in grimoireofgaia.cfg appears to have no effect on mob damage and little effect on heath. I observed that changing all health values to 50 (from 100) made a new wild spawned Minotaurus have 66 health instead of 80, but that's the only observed effect of changing anything so far. We're still getting crazy Minotaurus arrow one-shots out of the blue even with BaseDamage set to false and 50% damage, against full iron armor.

Spawn rates seem to be over the top for certain biomes from Biomes O' Plenty. Prairie spawns more Minotauruses than pigs, cows, and chickens combined. At very least, setting spawn rates to zero shows that this part of the config works and that the file is being used.

Version 1.4.8 with [Resonant Rise](https://www.atlauncher.com/pack/ResonantRise)

**Comment by DoctorWiggles** [comment] 2017-01-20 19:37
Can't seem to reproduce with a freshly installed Resonant Rise mod pack (version 4.1.0.0-b)

![2017-01-20_10 54 50](https://cloud.githubusercontent.com/assets/10700823/22161594/e8d282fa-deff-11e6-9da5-adb1a5911513.png)
Health Config:
This is what I got from setting Tier 3's down to 5%, which is correct for 8 out of their 160 sized pool.
I also of course checked that it was working for the other Tier mobs as well.

Attack Damage Config:
Checked this as well, was able to toggle them down to do 0 damage and so on.

Piercing Attacks (Basedamage) & Hardmode Archers:
Toggling them off worked as intended.

Spawn Rates:
Didn't investigate too thoroughly but increasing weights to 100, and decreasing others to 0 worked.
Flooding an area with a specific mob while the other was no where to be seen. Assuming it's fully functional as well in Biome's of Plenty.

//===================================================//

As far as I can tell everything looks like it's working. So a couple trouble shooting notes.

Archers:
For the Minotaurus archers potentially one shotting players, there's a config that was added in the 1.10 version for archers in hardmode to use enchanted arrows. It's similar to the Base damage piercing config. These apply a damaging potion and slowing potion to the victims. However the potion (magic damage) portion of the damage should only do like 4-8 damage tops. You didn't mention that you explicitly turned this config off - if you haven't flip it off - see if it drop their damage by a manageable amount. Even with it off, they shouldn't be one shotting full health armored players though.

Other Mods:
Another note is that the modpack could have a mod that's increasing the difficulty of monsters or something.  Like say as time progresses the mod would add stats to them - which could explain why I'm not seeing the issues on a fresh modpack and fresh map. 

//===================================================//

I'd suggest that you create a new instance from scratch, test again and see if the issues still persist.

**Comment by Ranzear** [comment] 2017-01-20 20:10
Yeah, it could be some other modpack. The 66 health on a tier 2 made no sense as I never used uh... 82.5? as a value.

This already is a fresh new instance.

I can't help but notice the biome in your screenshot. Are those wild spawns or debug spawns?

![image](https://cloud.githubusercontent.com/assets/981857/22163812/41f07cda-df09-11e6-82fb-1b604319981d.png)

This is with life set to 50. I'm so confused now. Maybe it's a line-endings thing from transferring the server from Windows like the nogui x11 bug...

**Comment by RaeveNoir** [comment] 2017-01-20 20:28
It's a new instance. I had to restart twice to get new settings to stick. So strange. Maybe this is an issue with using winscp to edit files and the change gets really delayed.

![image](https://cloud.githubusercontent.com/assets/981857/22164047/5402b1f8-df0a-11e6-9cf6-ba0fa253013b.png)

25% life

So something else is giving them 10% extra. I don't remember using 75% but with 10% more that'd explain the 66. Is that the vanilla 'hard' setting working differently in 1.10.2 maybe?

**Closed as completed** 2017-01-20 20:30 UTC

**Comment by DoctorWiggles** [comment] 2017-01-20 20:43
Those were natural spawns, had BOP set to tiny biomes so that might be why it looked funny.

I forgot to mention but some of the configurations you can change in game, but for most like the spawning, and attributes you need to reload the entire game for it to take effect.

As for the extra 10% I'm not sure. I'll take a look into it if 1.10 or so on added something like that.
